name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: |
          echo "HOLA MUNDO CON MI USUARIO EDISON DAVID!"
      - name: Dime la fecha
        run: date
      - run: ls -l